require ("joestar.plugins.telescope")
--require ("joestar.plugins.kanagawa")
--require ("joestar.plugins.cyberdream")
require ("joestar.plugins.treesitter")
require ("joestar.plugins.undotree")
require ("joestar.plugins.fugitive")
require ("joestar.plugins.lsp")
require ("joestar.plugins.lualine")
require ("joestar.plugins.catppuccin")
require ("joestar.plugins.42")
require ("joestar.plugins.presence")

